### ISSUE TITLE
issue #2, Landing Page

### ISSUE THREAD

**Issue by OspreyVelt** [sithSlave/game-finder#3]

**Comment by OspreyVelt** [comment]
*function to search for game by name 
	*fetch method with endpoint

**Comment by OneCrinkleyFry** [comment]
* create a landing page html page
* create a landing page js page
* create a variable that holds a hardcoded title for a game title
* use fetch to get the data
* display that data on the page

*once we get the search function functioning*
* replace the hardcoded variable with a dynamic game

**Comment by OneCrinkleyFry** [comment]
We are now doing a modal for this instead of a second page.
