### ISSUE TITLE
issue #4, Styling

### ISSUE THREAD

**Issue by OspreyVelt** [sithSlave/game-finder#5]

**Comment by vandana1499** [comment]
Hello, @OspreyVelt  will you please elaborate the issue.

**Comment by OneCrinkleyFry** [comment]
* style the HTML containers that are in the html file
* style the DOM Elements in the JS file specifically the Create Main card, by applying classes to the elements
* add custom styling to anything that Pure js does not offer with it's classes.
* use a mobile first approach
